### ISSUE TITLE
Try out GitHub Actions

### ISSUE THREAD

**Issue by nchlswhttkr** [nchlswhttkr/nchlswhttkr.github.io#2]
I've been added to the beta for GitHub actions, it would be nice to see if that can be employed here.

It would also mean I can get rid of the `/scripts` that set up Git hooks, and PRs (if people made them) would automatically deploy.

Something like the following (syntax is a rough suggestion, I've barely scanned the documentation))

```yaml
on:
  push:
    - dev # the working branch, not run on PRs

job:
  image: hugo # probably from the gitlab registry
  script:
    - hugo
    # push artifacts from 'public' to master, deploys to GitHub Pages
```
